kind: Service
apiVersion: v1
metadata:
  name: consumer-cpu
spec:
  selector:
    app: consumer-cpu
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-cpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-cpu
  template:
    metadata:
      labels:
        app: consumer-cpu
    spec:
      containers:
        - name: resource-consumer
          image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "25Mi"
              cpu: "50m"
            limits:
              memory: "50Mi"
              cpu: "100m"
#---
#
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: hpa-auto-scale
#  namespace: default
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: consumer-cpu
#  minReplicas: 1
#  maxReplicas: 8
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 50